CREATE TABLE IF NOT EXISTS request_mail (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    uidl VARCHAR(255) NOT NULL,
    message_id VARCHAR(1000) NULL,
    original_subject TEXT NOT NULL,
    request_title TEXT NULL,
    normalized_subject TEXT NULL,
    subject_hash CHAR(64) NULL,
    mail_body LONGTEXT NULL,
    sender_email VARCHAR(500) NULL,
    requester_user_id VARCHAR(128) NULL,
    reply_to_email VARCHAR(500) NULL,
    original_recipient_email VARCHAR(500) NULL,
    actual_recipient_email VARCHAR(500) NULL,
    recipient_mode VARCHAR(20) NULL,
    mail_sent_at DATETIME NULL,
    received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duplicate_of BIGINT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    retry_count INT NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    answer_text LONGTEXT NULL,
    search_results_json JSON NULL,
    chat_session_id VARCHAR(64) NULL,
    chat_turn_artifact_id VARCHAR(64) NULL,
    chat_search_log_id VARCHAR(64) NULL,
    send_status VARCHAR(30) NOT NULL DEFAULT 'NOT_READY',
    sent_mail_id VARCHAR(255) NULL,
    sent_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_request_mail_uidl (uidl),
    INDEX idx_request_mail_status (status),
    INDEX idx_request_mail_send_status (send_status),
    INDEX idx_request_mail_subject_hash (subject_hash),
    INDEX idx_request_mail_duplicate_of (duplicate_of)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
